import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createElement as h } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { TooltipProvider } from '../components/ui/tooltip';
import { WhoStep, WhatStep, validateStep } from '../components/webinar-workspace/setup';
import { RecruitmentView } from '../components/webinar-workspace/recruitment';

const wrap = (el: ReturnType<typeof h>) => renderToStaticMarkup(h(TooltipProvider, null, el));
const session = (suppress: boolean) => ({ sessionDate: '2026-05-12', startTime: '14:00', timezone: 'UTC', registrationRule: { suppressRecruitmentAfterRegistration: suppress } }) as never;
const whoProps = (suppress: boolean) => ({ session: session(suppress), summary: undefined, variants: [], errors: {}, setVariants: () => {}, draft: {} as never, setDraft: () => {}, campaign: undefined, standard: undefined, stage: undefined, goTo: () => {} }) as never;

test('Who step has no live suppression control; canonical requirement is read-only', () => {
  const html = wrap(h(WhoStep, whoProps(true)));
  assert.ok(!html.includes('switch-suppress'));
  assert.ok(!/role="switch"[^>]*Suppress/i.test(html));
  assert.match(html, /Read-only · required by the standard/);
});

test('legacy disabled suppression shows a warning and offers no bypass', () => {
  const html = wrap(h(WhoStep, whoProps(false)));
  assert.match(html, /legacy configuration with suppression disabled/);
  assert.match(html, /does not offer a way to keep it disabled or bypass it/);
  assert.ok(!html.includes('<button') || !/suppress/i.test(html.match(/<button[^>]*>[^<]*/g)?.join('') ?? ''));
});

const comm = { id: 'c1', key: 'recruitment_1', name: 'Recruitment 1', sortOrder: 1, status: 'executed', audienceRule: 'all', timing: { kind: 'relative', direction: 'before', offset: 7, unit: 'days' },
  scheduled: { status: 'sent', originalAt: '2020-01-01T00:00:00Z', currentAt: '2020-01-02T00:00:00Z', effectiveAt: '2020-01-02T00:00:00Z', skipReason: null },
  ctas: [{ id: 'x', name: 'Register', destinationUrl: 'https://x.test', status: 'planned' }], variants: [{ validation: { valid: true }, content: {} }] };
const view = (overdueSource: object) => wrap(h(RecruitmentView, { standard: { communications: [comm] } as never, session: session(true), stage: undefined, summary: undefined, overdueSource: overdueSource as never, onJumpSetup: () => {} }));

test('recruitment never fabricates sent, overdue, or complete', () => {
  const html = view({ status: 'unavailable', reason: 'Service unavailable.' });
  assert.match(html, /Overdue unknown/);
  assert.match(html, /Execution unknown/);
  assert.ok(!/>Sent</.test(html) && !/>Executed</.test(html));
  assert.ok(!/touch-overdue-recruitment_1[^>]*>(<[^>]+>)*Overdue</.test(html));
  assert.ok(!html.includes('Complete plans'));
  assert.match(html, /Plans with content and destination \(informational\)/);
  assert.match(html, /Simulation readiness \(non-operational\)/);
  assert.match(html, /no execution evidence/);
});

test('overdue shown only with backend authority and its as-of time', () => {
  const html = view({ status: 'ready', auth: { calculatedAt: '2026-03-01T00:00:00Z', byKey: { recruitment_1: { overdue: true, shortenedWindow: false } } } });
  assert.match(html, /data-testid="touch-overdue-recruitment_1"[^>]*>.*?Overdue</);
  assert.match(html, /backend preview/);
});

test('What step shows the working title read-only (no editable name input)', () => {
  const html = wrap(h(WhatStep, { ...(whoProps(true) as object), draft: { name: 'WEB-2026-Spring clinic', speakers: [] }, summary: undefined, standard: undefined } as never));
  assert.match(html, /data-testid="text-working-title"[^>]*>WEB-2026-Spring clinic</);
  assert.ok(!html.includes('id="ww-f-name"'));
  assert.match(html, /Add speaker/);
  assert.match(html, /not Foundation governed\. It cannot be edited through the current API/);
  assert.ok(!/naming service|generated by/i.test(html));
  assert.deepEqual(validateStep('what', { name: '', speakers: [] } as never, []), {}, 'empty governed name is not a user error');
});

test('regression: drawer does not request the policy-blocked webinar people list; shell nav wraps to icons', async () => {
  const { readFileSync } = await import('node:fs');
  const panel = readFileSync(new URL('../components/map/WebinarStandardPanel.tsx', import.meta.url), 'utf8');
  assert.match(panel, /enabled: Boolean\(campaignId && sessionId\) && devStatus\.isSuccess && !openDevelopment/);
  assert.ok(!/enabled: false/.test(panel), 'people list not globally disabled');
  const layout = readFileSync(new URL('../components/layout.tsx', import.meta.url), 'utf8');
  assert.match(layout, /overflow-x-auto/); assert.match(layout, /hidden lg:inline">\{item\.label\}/);
});
