export type FoundationTaxonomySeedRow = {
  tagCode: string;
  parentStableKey: string | null;
  stableKey: string;
  displayName: string;
};

export const foundationProductLines: readonly FoundationTaxonomySeedRow[] = [
  { tagCode: "analytics", parentStableKey: null, stableKey: "product_line:analytics", displayName: "Analytics" },
  { tagCode: "climate", parentStableKey: null, stableKey: "climate", displayName: "Climate" },
  { tagCode: "index", parentStableKey: null, stableKey: "product_line:index", displayName: "Index" },
  { tagCode: "onemsci", parentStableKey: null, stableKey: "onemsci", displayName: "OneMSCI" },
  { tagCode: "privateasset", parentStableKey: null, stableKey: "privateasset", displayName: "Private Asset" },
  { tagCode: "sustainb", parentStableKey: null, stableKey: "sustainb", displayName: "Sustainability" },
  { tagCode: "wealth", parentStableKey: null, stableKey: "wealth", displayName: "Wealth" },
] as const;

export const foundationCampaignShortcodes: readonly FoundationTaxonomySeedRow[] = [
  { tagCode: "bau", parentStableKey: "product_line:analytics", stableKey: "campaign_shortcode:analytics:bau", displayName: "Business as Usual" },
  { tagCode: "fut-risk", parentStableKey: "product_line:analytics", stableKey: "fut-risk", displayName: "Future of Risk and Performance Management" },
  { tagCode: "pow-port", parentStableKey: "product_line:analytics", stableKey: "pow-port", displayName: "Powering the Front Office to Build Resilient Portfolios" },
  { tagCode: "tps", parentStableKey: "product_line:analytics", stableKey: "campaign_shortcode:analytics:tps", displayName: "Total Portfolio Analytics / Solutions" },
  { tagCode: "value", parentStableKey: "product_line:analytics", stableKey: "value", displayName: "Reinforcing Value" },
  { tagCode: "bau", parentStableKey: "climate", stableKey: "campaign_shortcode:climate:bau", displayName: "Business as Usual" },
  { tagCode: "climate-series", parentStableKey: "climate", stableKey: "climate-series", displayName: "Climate Series" },
  { tagCode: "me-crisis", parentStableKey: "climate", stableKey: "campaign_shortcode:climate:me-crisis", displayName: "Middle East Crisis" },
  { tagCode: "phys-risk", parentStableKey: "climate", stableKey: "phys-risk", displayName: "Physical Risk" },
  { tagCode: "transition", parentStableKey: "climate", stableKey: "transition", displayName: "Transition Opportunities to Catalyze Growth" },
  { tagCode: "trends", parentStableKey: "climate", stableKey: "campaign_shortcode:climate:trends", displayName: "Trends in Focus" },
  { tagCode: "bau", parentStableKey: "product_line:index", stableKey: "campaign_shortcode:index:bau", displayName: "Business as Usual" },
  { tagCode: "i4e", parentStableKey: "product_line:index", stableKey: "i4e", displayName: "An Index for Each" },
  { tagCode: "i4w", parentStableKey: "product_line:index", stableKey: "i4w", displayName: "Expansion into the Wealth Channel" },
  { tagCode: "leadership", parentStableKey: "product_line:index", stableKey: "leadership", displayName: "Reinforcing the MSCI Index Dominance" },
  { tagCode: "bau", parentStableKey: "onemsci", stableKey: "campaign_shortcode:onemsci:bau", displayName: "Business as Usual" },
  { tagCode: "corp-act-eng", parentStableKey: "onemsci", stableKey: "campaign_shortcode:onemsci:corp-act-eng", displayName: "Corporate Activation Engine" },
  { tagCode: "employer_brand", parentStableKey: "onemsci", stableKey: "employer_brand", displayName: "Employer Brand" },
  { tagCode: "institute", parentStableKey: "onemsci", stableKey: "campaign_shortcode:onemsci:institute", displayName: "Institute" },
  { tagCode: "institutional-investor-forum", parentStableKey: "onemsci", stableKey: "institutional-investor-forum", displayName: "Institutional Investor Forum" },
  { tagCode: "inv-summit", parentStableKey: "onemsci", stableKey: "inv-summit", displayName: "Investor Summit" },
  { tagCode: "mstrbr", parentStableKey: "onemsci", stableKey: "mstrbr", displayName: "Masterbrand" },
  { tagCode: "recruitment_marketing", parentStableKey: "onemsci", stableKey: "recruitment_marketing", displayName: "Recruitment Marketing" },
  { tagCode: "research", parentStableKey: "onemsci", stableKey: "campaign_shortcode:onemsci:research", displayName: "Research" },
  { tagCode: "tariff-hub", parentStableKey: "onemsci", stableKey: "tariff-hub", displayName: "Tariff Hub" },
  { tagCode: "trends", parentStableKey: "onemsci", stableKey: "campaign_shortcode:onemsci:trends", displayName: "Trends in Focus" },
  { tagCode: "bau", parentStableKey: "privateasset", stableKey: "campaign_shortcode:privateasset:bau", displayName: "Business as Usual" },
  { tagCode: "benchmkg", parentStableKey: "privateasset", stableKey: "benchmkg", displayName: "Benchmarking" },
  { tagCode: "expansion", parentStableKey: "privateasset", stableKey: "expansion", displayName: "Powering Private Asset Allocation & Expansion" },
  { tagCode: "fam-off", parentStableKey: "privateasset", stableKey: "fam-off", displayName: "Family Office" },
  { tagCode: "gp-solutions", parentStableKey: "privateasset", stableKey: "gp-solutions", displayName: "GP Solutions" },
  { tagCode: "me-crisis", parentStableKey: "privateasset", stableKey: "campaign_shortcode:privateasset:me-crisis", displayName: "Middle East Crisis" },
  { tagCode: "pa-ai-infra", parentStableKey: "privateasset", stableKey: "pa-ai-infra", displayName: "PA AI Infrastructure" },
  { tagCode: "pa-indx", parentStableKey: "privateasset", stableKey: "pa-indx", displayName: "PA Index" },
  { tagCode: "priv-cred-sols", parentStableKey: "privateasset", stableKey: "priv-cred-sols", displayName: "Private Credit Solutions" },
  { tagCode: "re-opp", parentStableKey: "privateasset", stableKey: "re-opp", displayName: "Capitalize on Real Estate Opportunities" },
  { tagCode: "tps", parentStableKey: "privateasset", stableKey: "campaign_shortcode:privateasset:tps", displayName: "Total Portfolio Solutions" },
  { tagCode: "trends", parentStableKey: "privateasset", stableKey: "campaign_shortcode:privateasset:trends", displayName: "Trends in Focus" },
  { tagCode: "bau", parentStableKey: "sustainb", stableKey: "campaign_shortcode:sustainb:bau", displayName: "Business as Usual" },
  { tagCode: "corp-act-eng", parentStableKey: "sustainb", stableKey: "campaign_shortcode:sustainb:corp-act-eng", displayName: "Corporate Activation Engine" },
  { tagCode: "institute", parentStableKey: "sustainb", stableKey: "campaign_shortcode:sustainb:institute", displayName: "Institute" },
  { tagCode: "me-crisis", parentStableKey: "sustainb", stableKey: "campaign_shortcode:sustainb:me-crisis", displayName: "Middle East Crisis" },
  { tagCode: "regulatory", parentStableKey: "sustainb", stableKey: "regulatory", displayName: "Regulations" },
  { tagCode: "sust-intel", parentStableKey: "sustainb", stableKey: "sust-intel", displayName: "Sustainability Intelligence to Drive Stronger Financial Outcomes" },
  { tagCode: "trends", parentStableKey: "sustainb", stableKey: "campaign_shortcode:sustainb:trends", displayName: "Trends in Focus" },
  { tagCode: "analytics", parentStableKey: "wealth", stableKey: "campaign_shortcode:wealth:analytics", displayName: "Grow Wealth Management Portfolio Personalization" },
  { tagCode: "bau", parentStableKey: "wealth", stableKey: "campaign_shortcode:wealth:bau", displayName: "Business as Usual" },
  { tagCode: "brand", parentStableKey: "wealth", stableKey: "campaign_shortcode:wealth:brand", displayName: "Promote the Global OneMSCI Wealth Brand" },
  { tagCode: "dirct-indx", parentStableKey: "wealth", stableKey: "dirct-indx", displayName: "Drive Index-Linked ABF from the Wealth Segment" },
  { tagCode: "me-crisis", parentStableKey: "wealth", stableKey: "campaign_shortcode:wealth:me-crisis", displayName: "Middle East Crisis" },
  { tagCode: "trends", parentStableKey: "wealth", stableKey: "campaign_shortcode:wealth:trends", displayName: "Trends in Focus" },
] as const;

export const foundationSubcampaigns: readonly FoundationTaxonomySeedRow[] = [
  { tagCode: "pm-persp", parentStableKey: "campaign_shortcode:analytics:bau", stableKey: "pm-persp", displayName: "MSCI Portfolio Management Perspectives" },
  { tagCode: "recurring-events", parentStableKey: "campaign_shortcode:analytics:bau", stableKey: "subcampaign:analytics/bau:recurring-events", displayName: "Recurring Events" },
  { tagCode: "risk-mgmt-dig", parentStableKey: "campaign_shortcode:analytics:bau", stableKey: "risk-mgmt-dig", displayName: "MSCI Risk Management Digest" },
  { tagCode: "aipi", parentStableKey: "fut-risk", stableKey: "aipi", displayName: "AI Portfolio Insights" },
  { tagCode: "aon", parentStableKey: "fut-risk", stableKey: "subcampaign:analytics/fut-risk:aon", displayName: "AON" },
  { tagCode: "cstm-co", parentStableKey: "fut-risk", stableKey: "cstm-co", displayName: "Custom Covariance" },
  { tagCode: "mvr", parentStableKey: "fut-risk", stableKey: "mvr", displayName: "Multidimension View of Risk" },
  { tagCode: "cons-alm", parentStableKey: "pow-port", stableKey: "cons-alm", displayName: "Construction - ALM" },
  { tagCode: "cons-bb", parentStableKey: "pow-port", stableKey: "cons-bb", displayName: "Construction - Basket Builder" },
  { tagCode: "cons-efm", parentStableKey: "pow-port", stableKey: "cons-efm", displayName: "Construction - Equity Factor Models" },
  { tagCode: "cons-fi", parentStableKey: "pow-port", stableKey: "cons-fi", displayName: "Construction - Fixed Income Factor Models" },
  { tagCode: "cons-ssa", parentStableKey: "pow-port", stableKey: "cons-ssa", displayName: "Construction - Single Security Analytics" },
  { tagCode: "inv-flabs", parentStableKey: "pow-port", stableKey: "inv-flabs", displayName: "Innovation - Factor Labs" },
  { tagCode: "inv-sl", parentStableKey: "pow-port", stableKey: "inv-sl", displayName: "Innovation - Signal Library" },
  { tagCode: "ux-aipi", parentStableKey: "pow-port", stableKey: "ux-aipi", displayName: "UX - AI Portfolio Insights" },
  { tagCode: "ux-bpm", parentStableKey: "pow-port", stableKey: "ux-bpm", displayName: "UX - Barra Portfolio Manager" },
  { tagCode: "ux-edd", parentStableKey: "pow-port", stableKey: "ux-edd", displayName: "UX - Event Driven Data Set" },
  { tagCode: "ux-patt", parentStableKey: "pow-port", stableKey: "ux-patt", displayName: "UX - Performance Attribution" },
  { tagCode: "barra1", parentStableKey: "campaign_shortcode:analytics:tps", stableKey: "subcampaign:analytics/tps:barra1", displayName: "BarraOne" },
  { tagCode: "factor", parentStableKey: "campaign_shortcode:analytics:tps", stableKey: "factor", displayName: "Factor" },
  { tagCode: "pcs", parentStableKey: "campaign_shortcode:analytics:tps", stableKey: "pcs", displayName: "PCS Transparency Benchmark" },
  { tagCode: "cop31", parentStableKey: "climate-series", stableKey: "cop31", displayName: "COP31" },
  { tagCode: "lcaw", parentStableKey: "climate-series", stableKey: "lcaw", displayName: "London Climate Action Week" },
  { tagCode: "nycaw", parentStableKey: "climate-series", stableKey: "nycaw", displayName: "New York Climate Week" },
  { tagCode: "zurich", parentStableKey: "climate-series", stableKey: "zurich", displayName: "Zurich Climate Week" },
  { tagCode: "first-street", parentStableKey: "phys-risk", stableKey: "first-street", displayName: "First Street Acquisition" },
  { tagCode: "geospatial", parentStableKey: "phys-risk", stableKey: "geospatial", displayName: "Geospatial" },
  { tagCode: "issuer-phys-risk", parentStableKey: "phys-risk", stableKey: "issuer-phys-risk", displayName: "Issuer Physical Risk" },
  { tagCode: "nature-bio", parentStableKey: "phys-risk", stableKey: "nature-bio", displayName: "Nature and Biodiversity" },
  { tagCode: "phys-risk-asset", parentStableKey: "phys-risk", stableKey: "phys-risk-asset", displayName: "Physical Risk Asset Level" },
  { tagCode: "supply-chain", parentStableKey: "phys-risk", stableKey: "supply-chain", displayName: "Supply Chain" },
  { tagCode: "carbon-markets", parentStableKey: "transition", stableKey: "carbon-markets", displayName: "Carbon Markets" },
  { tagCode: "ccap", parentStableKey: "transition", stableKey: "ccap", displayName: "CCAP Regulation for Climate" },
  { tagCode: "cop-30", parentStableKey: "transition", stableKey: "cop-30", displayName: "Cop 30" },
  { tagCode: "transition-framework", parentStableKey: "transition", stableKey: "transition-framework", displayName: "Energy Transition Framework" },
  { tagCode: "index-ai-insights", parentStableKey: "campaign_shortcode:index:bau", stableKey: "index-ai-insights", displayName: "Index AI Insights MCP Handraiser Always On" },
  { tagCode: "mkt-ins", parentStableKey: "campaign_shortcode:index:bau", stableKey: "mkt-ins", displayName: "MSCI Market Insights" },
  { tagCode: "recurring-events", parentStableKey: "campaign_shortcode:index:bau", stableKey: "subcampaign:index/bau:recurring-events", displayName: "Recurring Events" },
  { tagCode: "clim-indx", parentStableKey: "i4e", stableKey: "clim-indx", displayName: "Climate Indexes" },
  { tagCode: "clim-sust-indx", parentStableKey: "i4e", stableKey: "clim-sust-indx", displayName: "Climate and Sustainability Indexes" },
] as const;

export const foundationTaxonomySeed = [
  ...foundationProductLines.map((row) => ({ ...row, category: "product_line" as const })),
  ...foundationCampaignShortcodes.map((row) => ({ ...row, category: "campaign_shortcode" as const })),
  ...foundationSubcampaigns.map((row) => ({ ...row, category: "subcampaign" as const })),
] as const;